#!/usr/bin/env php
<?php
use HTTPServer\Server;
use HTTPServer\Response;
use HTTPServer\Request;

array_shift($argv);

empty($argv) ? $port = 80 : $port = array_shift($argv);

require 'vendor/autoload.php';

$server = new Server('127.0.0.1', $port);

$server->listen(function (Request $request) {
    return new Response('Hello World!');
});